import { describe, expect, test } from "bun:test";
import fastCheck from "fast-check";

import type { LinkedImageSection } from "../../../src/linker";
import {
  PE_IMAGE_REL_BASED_DIR64,
  alignPe,
  parsePeCoffImage,
  planPeCoffSections,
  serializePeBaseRelocations,
} from "../../../src/pe-coff";
import {
  dir64RelocationForTest,
  linkedImageLayoutForPeCoffTest,
  writerTargetForTest,
} from "../../support/pe-coff/pe-coff-fixtures";

const FAST_CHECK_OPTIONS = { numRuns: 35, seed: 15015 };
const SECTION_ALIGNMENT_BYTES = 0x1000;
const TEXT_SECTION_FLAGS = 0x60000020;
const READ_ONLY_SECTION_FLAGS = 0x40000040;
const DATA_SECTION_FLAGS = 0xc0000040;

describe("PE/COFF writer properties", () => {
  test("base relocation serialization round-trips generated unique DIR64 RVAs", () => {
    fastCheck.assert(
      fastCheck.property(
        fastCheck.uniqueArray(fastCheck.integer({ min: 0x1000, max: 0x1ffff }), {
          selector: (rva) => rva,
          minLength: 1,
          maxLength: 32,
        }),
        (rvas) => {
          const relocations = rvas.map((rva, index) =>
            dir64RelocationForTest({ stableKey: `property-reloc:${index}`, rva }),
          );

          const serialized = serializePeBaseRelocations({
            target: writerTargetForTest(),
            relocations,
          });

          expect(serialized.kind).toBe("ok");
          if (serialized.kind !== "ok") throw new Error("expected relocation bytes");
          const parsed = parseBaseRelocationBlocksForTest(serialized.value.bytes);
          expect(parsed.kind).toBe("ok");
          if (parsed.kind !== "ok") throw new Error("expected parsed relocations");
          expect([...parsed.value].sort((left, right) => left - right)).toEqual(
            [...rvas].sort((left, right) => left - right),
          );
        },
      ),
      FAST_CHECK_OPTIONS,
    );
  });

  test("section raw offsets remain contiguous and aligned for generated byte lengths", () => {
    fastCheck.assert(
      fastCheck.property(sectionByteLengths(), (byteLengths) => {
        const target = writerTargetForTest();
        const layout = linkedImageLayoutForPeCoffTest({
          sections: sectionsForByteLengths(byteLengths),
          dataDirectorySources: [
            {
              stableKey: "data-directory:exception:.pdata",
              directoryKind: "exception",
              sectionKey: ".pdata",
              rva: 0x2000,
              sizeBytes: Math.max(1, byteLengths.pdata),
            },
          ],
          includeDataSection: false,
        });

        const result = planPeCoffSections({
          target,
          layout,
          baseRelocationTableBytes: [],
        });

        expect(result.kind).toBe("ok");
        if (result.kind !== "ok") throw new Error("expected planned sections");
        let expectedRawOffset = result.value.sizeOfHeadersBytes;
        for (const section of result.value.sections) {
          expect(section.rawDataPointerBytes).toBe(expectedRawOffset);
          expect(section.rawDataPointerBytes % target.fileAlignmentBytes).toBe(0);
          expect(section.rawDataSizeBytes).toBe(
            alignPe(section.bytes.length, target.fileAlignmentBytes),
          );
          expectedRawOffset += section.rawDataSizeBytes;
        }
        expect(result.value.sizeOfImageBytes).toBeLessThanOrEqual(target.maxImageSizeBytes);
      }),
      FAST_CHECK_OPTIONS,
    );
  });

  test("parser returns a result instead of throwing for arbitrary byte arrays", () => {
    fastCheck.assert(
      fastCheck.property(
        fastCheck.array(fastCheck.integer({ min: 0, max: 0xff }), { maxLength: 768 }),
        (bytes) => {
          let result: ReturnType<typeof parsePeCoffImage> | undefined;
          expect(() => {
            result = parsePeCoffImage(bytes);
          }).not.toThrow();
          expect(result?.kind === "ok" || result?.kind === "error").toBe(true);
        },
      ),
      FAST_CHECK_OPTIONS,
    );
  });
});

function sectionByteLengths() {
  return fastCheck.record({
    text: fastCheck.integer({ min: 1, max: 4096 }),
    pdata: fastCheck.integer({ min: 1, max: 1024 }),
    xdata: fastCheck.integer({ min: 1, max: 1024 }),
    data: fastCheck.integer({ min: 1, max: 4096 }),
  });
}

function sectionsForByteLengths(byteLengths: {
  readonly text: number;
  readonly pdata: number;
  readonly xdata: number;
  readonly data: number;
}): readonly LinkedImageSection[] {
  return [
    linkedSection(".text", 0x1000, byteLengths.text, TEXT_SECTION_FLAGS),
    linkedSection(".pdata", 0x2000, byteLengths.pdata, READ_ONLY_SECTION_FLAGS),
    linkedSection(".xdata", 0x3000, byteLengths.xdata, READ_ONLY_SECTION_FLAGS),
    linkedSection(".data", 0x4000, byteLengths.data, DATA_SECTION_FLAGS),
  ];
}

function linkedSection(
  stableKey: string,
  rva: number,
  byteLength: number,
  flags: number,
): LinkedImageSection {
  return {
    stableKey,
    classKey: stableKey,
    flags,
    alignmentBytes: SECTION_ALIGNMENT_BYTES,
    rva,
    virtualSizeBytes: byteLength,
    bytes: Uint8Array.from({ length: byteLength }, (_unusedValue, index) => index & 0xff),
    contributions: [
      {
        stableKey: `contribution:${stableKey}`,
        sourceModuleKey: "module:test",
        sourceObjectSectionKey: stableKey,
        sourceObjectSectionClass: stableKey,
        outputSectionKey: stableKey,
        offsetBytes: 0,
        sizeBytes: byteLength,
        alignmentBytes: 1,
      },
    ],
  };
}

function parseBaseRelocationBlocksForTest(
  bytes: ArrayLike<number>,
): { readonly kind: "ok"; readonly value: readonly number[] } | { readonly kind: "error" } {
  const relocationRvas: number[] = [];
  let cursor = 0;
  while (cursor < bytes.length) {
    if (cursor + 8 > bytes.length) return { kind: "error" };
    const pageRva = readU32Le(bytes, cursor);
    const blockSizeBytes = readU32Le(bytes, cursor + 4);
    if (blockSizeBytes < 8 || blockSizeBytes % 4 !== 0 || cursor + blockSizeBytes > bytes.length) {
      return { kind: "error" };
    }
    for (let entryOffset = cursor + 8; entryOffset < cursor + blockSizeBytes; entryOffset += 2) {
      const encodedEntry = readU16Le(bytes, entryOffset);
      const type = encodedEntry >> 12;
      const offset = encodedEntry & 0x0fff;
      if (type === PE_IMAGE_REL_BASED_DIR64) relocationRvas.push(pageRva + offset);
    }
    cursor += blockSizeBytes;
  }
  return { kind: "ok", value: relocationRvas };
}

function readU16Le(bytes: ArrayLike<number>, offset: number): number {
  return (bytes[offset] ?? 0) | ((bytes[offset + 1] ?? 0) << 8);
}

function readU32Le(bytes: ArrayLike<number>, offset: number): number {
  return (
    ((bytes[offset] ?? 0) |
      ((bytes[offset + 1] ?? 0) << 8) |
      ((bytes[offset + 2] ?? 0) << 16) |
      ((bytes[offset + 3] ?? 0) * 2 ** 24)) >>>
    0
  );
}
