import Wrela.ProofMIR.Model0
import Wrela.ProofMIR.Model1
import Wrela.ProofMIR.Model2
import Wrela.ProofMIR.Model3
import Wrela.ProofMIR.Model4
import Wrela.ProofMIR.Model5
import Wrela.ProofMIR.Model6
import Wrela.ProofMIR.Model7
import Wrela.ProofMIR.Model8
import Wrela.ProofMIR.Model9
import Wrela.ProofMIR.Model10
import Wrela.ProofMIR.Model11
import Wrela.ProofMIR.Model12
