export {
  linkAArch64Image,
  materializeAArch64SyntheticObjectsForLink,
  type AArch64ImageEntryRequest,
  type AArch64LinkInputModule,
  type AArch64LinkerVeneerProvider,
  type AArch64LinkerVeneerProviderInput,
  type AArch64LinkerVeneerProviderResult,
  type AArch64SyntheticObjectModule,
  type AArch64SyntheticObjectProvider,
  type AArch64SyntheticObjectProviderInput,
  type AArch64SyntheticObjectProviderResult,
  type LinkAArch64ImageInput,
  type LinkAArch64ImageResult,
  type MaterializeAArch64SyntheticObjectsForLinkInput,
  type MaterializedAArch64LinkInputModules,
} from "./aarch64/aarch64-linker";
export {
  createAArch64LinkedImageLayout,
  type AArch64LinkedImageDeterministicMetadata,
  type AArch64LinkedImageEntry,
  type AArch64LinkedImageLayout,
  type AppliedRelocation,
  type CreateAArch64LinkedImageLayoutInput,
  type ImageBaseRelocation,
  type LinkedByteProvenance,
  type LinkedDataDirectorySource,
  type LinkedFactSpendingRecord,
  type LinkedImageInputModule,
  type LinkedImageSection,
  type LinkedUnwindRecord,
  type ResolvedImageSymbol,
  type SectionContribution,
} from "./linked-image-layout";
export {
  authenticateAArch64LinkerTargetSurface,
  type AArch64BaseRelocationPolicy,
  type AArch64ContributionAlignmentPolicy,
  type AArch64EntryPolicy,
  type AArch64LinkerTargetConstants,
  type AArch64LinkerTargetSurface,
  type AArch64LinkerTargetSurfaceInput,
  type AArch64RelocationFamilyPolicy,
  type AArch64SectionMappingPolicy,
} from "./image-layout-policy";
export { relocationKeyFor } from "./stable-keys";
export {
  createAArch64UefiEntrySyntheticObjectProvider,
  createAArch64UnwindSyntheticObjectProvider,
  type AArch64EntryObjectFactoryInput,
  type AArch64EntryObjectRelocationFactoryOutput,
  type AArch64SyntheticEntryObjectFactoryResult,
  type AArch64SyntheticObjectFactory,
  type AArch64SyntheticObjectFactoryError,
  type AArch64SyntheticUnwindObjectFactoryResult,
  type AArch64SyntheticUnwindSourceRecord,
  type AArch64UnwindObjectFactoryInput,
  type AArch64UnwindObjectFactoryOutput,
  type AArch64UnwindObjectRelocationFactoryOutput,
  type CreateAArch64SyntheticObjectProviderInput,
} from "./aarch64/aarch64-entry-objects";
export {
  type LinkerDiagnostic,
  type LinkerDiagnosticCode,
  type LinkerDiagnosticMode,
  type LinkerVerificationSummary,
  type LinkerVerifierRun,
} from "./diagnostics";
