export {
  LAYOUT_DIAGNOSTIC_CODES,
  layoutDiagnostic,
  layoutDiagnosticCode,
  sortLayoutDiagnostics,
} from "./diagnostics";
export type { LayoutDiagnostic, LayoutDiagnosticCode, LayoutDiagnosticInput } from "./diagnostics";

export type {
  LayoutBuilderContext,
  LayoutBuilderDependency,
  LayoutBuilderIssue,
  LayoutBuilderResult,
  LayoutOwnerKey,
} from "./builder-context";

export type { LayoutOwner } from "./layout-owners";
export {
  layoutOwnerToKey,
  parseLayoutOwnerKey,
  enrichDependenciesForOwner,
  validatedBufferRootOwnerKey,
  validatedBufferFieldOwnerKey,
  validatedBufferDerivedOwnerKey,
  validatedBufferTermOwnerKey,
  validatedBufferValueStorageOwnerKey,
  validatedBufferRootCauseKey,
  typeLayoutOwnerKey,
  enumLayoutOwnerKey,
  targetLayoutOwnerKey,
  functionAbiOwnerKey,
  functionsAbiOwnerKey,
  platformEdgeOwnerKey,
  platformEdgesOwnerKey,
  imageOwnerKey,
  imageDeviceOwnerKey,
  imageEntryFacetOwnerKey,
  layoutTypeOwnerKey,
  wireOwnerKey,
  derivedFieldFactsOwnerKey,
} from "./layout-owners";

export type {
  LayoutCanonicalKeyString,
  TargetCallConventionId,
  TargetWireReadHelperId,
} from "./ids";

export type {
  AbiClassificationUse,
  AbiScalarKind,
  ClassifyAbiValueInput,
  ClassifyAbiValueResult,
  LayoutDeviceSurfaceCatalog,
  LayoutDeviceSurfaceSpec,
  LayoutImageProfileArgumentSpec,
  LayoutImageProfileCatalog,
  LayoutImageProfileResultSpec,
  LayoutImageProfileSpec,
  LayoutPrimitiveKind,
  LayoutPrimitiveTypeCatalog,
  LayoutPrimitiveTypeRef,
  LayoutPrimitiveTypeSpec,
  LayoutTargetSurface,
  LayoutWireReadHelperCatalog,
  LayoutWireReadHelperSpec,
  TargetAbiSurface,
  TargetDataModelFacts,
  TargetEnumLayoutPolicy,
  TargetValidatedBufferHandleLayout,
  WireEndian,
  WireIntegerEncoding,
  WireScalarEncoding,
} from "./target-layout";
export { targetDefinitionDiagnostic, validateLayoutTargetSurface } from "./target-layout";
export { layoutTypeKeyFromPrimitiveRef, normalizeTargetFactsFromSurface } from "./target-facts";

export {
  layoutDeterministicTable,
  layoutFieldKeyString,
  layoutImageDeviceKeyString,
  layoutTypeFingerprintTable,
  layoutTypeKeyString,
  publishedLayoutTypeKeyToLayoutTypeKey,
} from "./type-key";

export { computeRepresentationLayoutFacts } from "./layout-fact-builder";

export type {
  ComputeRepresentationLayoutFactsInput,
  ComputeRepresentationLayoutFactsResult,
  LayoutAbiHiddenParameterFact,
  LayoutAbiLane,
  LayoutAbiParameterFact,
  LayoutAbiPointerProvenance,
  LayoutAbiPointerShape,
  LayoutAbiReturnFact,
  LayoutAbiStackRequirement,
  LayoutAbiValueShape,
  LayoutAggregateStorageFact,
  LayoutDerivedCaseCondition,
  LayoutDerivedCaseFact,
  LayoutDeterministicTable,
  LayoutEnumCaseFact,
  LayoutEnumFact,
  LayoutEnumFactTable,
  LayoutFactProgram,
  LayoutFieldFact,
  LayoutFieldFactTable,
  LayoutFieldKey,
  LayoutFunctionAbiFact,
  LayoutFunctionAbiFactTable,
  LayoutHiddenStorageField,
  LayoutImageDeviceFact,
  LayoutImageDeviceFactTable,
  LayoutImageDeviceKey,
  LayoutImageEntryAbiFact,
  LayoutImageEntryThunkConversion,
  LayoutIntegerRange,
  LayoutPaddingRange,
  LayoutPlatformAbiFact,
  LayoutPlatformAbiFactTable,
  LayoutReadRequirement,
  LayoutTerm,
  LayoutTermUnit,
  LayoutTypeFact,
  LayoutTypeFactTable,
  LayoutTypeKey,
  LayoutTypeRepresentation,
  LayoutValidatedBufferDerivedFact,
  LayoutValidatedBufferFact,
  LayoutValidatedBufferFactTable,
  LayoutValidatedBufferFieldFact,
  LayoutValidatedBufferValueStorageFact,
  LayoutWireAggregateFieldFact,
  LayoutWireReadPolicy,
  LayoutWireReservedRange,
  LayoutWireTypeFact,
  TargetLayoutFacts,
} from "./layout-program";
